<?php

namespace Database\Seeders;

use App\Models\RealEstateListing;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

class RealEstateListingSeeder extends Seeder
{
    public function run(): void
    {
        $defaultFeatures = ['Central AC', 'Central Heat', 'Updated Kitchen', 'Fenced Yard', 'Garage'];

        $items = [
            [
                'title' => 'Single Family Home in Alief',
                'property_type' => 'Single Family',
                'listing_type' => 'sale',
                'price' => 265000,
                'address' => '11218 Bellaire Boulevard',
                'city' => 'Alief', 'state' => 'Texas', 'zip' => '77072',
                'subdivision' => 'Alief Estates',
                'bedrooms' => 3, 'full_bathrooms' => 2, 'half_bathrooms' => 0,
                'square_feet' => 1580, 'lot_size' => 6200, 'year_built' => 2004,
                'description' => "Cozy single-family home in a quiet Alief neighborhood. Updated kitchen, open living area, and a fenced backyard. Close to schools, shopping, and major freeways.",
                'features' => array_merge($defaultFeatures, ['Tile Floors', 'Covered Patio']),
                'photo' => 'alief.jpeg',
                'latitude' => 29.7066, 'longitude' => -95.5897,
            ],
            [
                'title' => 'Ranch Home in Cypress',
                'property_type' => 'Single Family',
                'listing_type' => 'sale',
                'price' => 389000,
                'address' => '14206 Windmill Ridge',
                'city' => 'Cypress', 'state' => 'Texas', 'zip' => '77429',
                'subdivision' => 'Bridgeland',
                'bedrooms' => 4, 'full_bathrooms' => 3, 'half_bathrooms' => 0,
                'square_feet' => 2780, 'lot_size' => 8100, 'year_built' => 2012,
                'description' => "Spacious ranch-style home on a corner lot with mature trees. Open kitchen with island and breakfast bar. Bridgeland community pools, trails, and parks.",
                'features' => array_merge($defaultFeatures, ['Mature Trees', 'Sprinkler System', 'Covered Patio']),
                'photo' => 'cypress.jpeg',
                'latitude' => 29.9691, 'longitude' => -95.6913,
            ],
            [
                'title' => 'New Construction in Fort Bend County',
                'property_type' => 'Single Family',
                'listing_type' => 'sale',
                'price' => 459000,
                'address' => '2305 Fort Bend Parkway',
                'city' => 'Sugar Land', 'state' => 'Texas', 'zip' => '77479',
                'subdivision' => 'Riverstone',
                'bedrooms' => 4, 'full_bathrooms' => 3, 'half_bathrooms' => 1,
                'square_feet' => 3120, 'lot_size' => 7500, 'year_built' => 2023,
                'description' => "Brand new construction in master-planned Riverstone. Two-story with study, game room, and covered patio. Energy efficient with smart-home wiring.",
                'features' => array_merge($defaultFeatures, ['Smart Home', 'Stainless Steel Appliances', 'Walk-In Closet']),
                'photo' => 'fort-bend-county.jpeg',
                'latitude' => 29.5830, 'longitude' => -95.5694,
            ],
            [
                'title' => 'Modern Home in Fulshear',
                'property_type' => 'Single Family',
                'listing_type' => 'sale',
                'price' => 519000,
                'address' => '7418 Cross Creek Bend',
                'city' => 'Fulshear', 'state' => 'Texas', 'zip' => '77441',
                'subdivision' => 'Cross Creek Ranch',
                'bedrooms' => 4, 'full_bathrooms' => 3, 'half_bathrooms' => 1,
                'square_feet' => 3250, 'lot_size' => 8400, 'year_built' => 2021,
                'description' => "Beautiful modern home in Fulshear's award-winning Cross Creek Ranch. Open floor plan, chef's kitchen, and a covered outdoor living area.",
                'features' => array_merge($defaultFeatures, ['Hardwood Floors', 'Granite Countertops', 'Covered Patio']),
                'photo' => 'fulshear.jpeg',
                'latitude' => 29.6930, 'longitude' => -95.8988,
            ],
            [
                'title' => 'Coastal Retreat in Galveston',
                'property_type' => 'Single Family',
                'listing_type' => 'sale',
                'price' => 549000,
                'address' => '1820 Seawall Boulevard',
                'city' => 'Galveston', 'state' => 'Texas', 'zip' => '77550',
                'subdivision' => 'East End Historic District',
                'bedrooms' => 3, 'full_bathrooms' => 2, 'half_bathrooms' => 1,
                'square_feet' => 2150, 'lot_size' => 5000, 'year_built' => 1998,
                'description' => "Charming coastal home just blocks from the beach. Wrap-around porch, updated interior, and short-term rental friendly. Perfect second home or investment.",
                'features' => array_merge($defaultFeatures, ['Balcony', 'Hardwood Floors']),
                'photo' => 'galveston.jpeg',
                'latitude' => 29.3013, 'longitude' => -94.7977,
            ],
            [
                'title' => 'Starter Home in Humble',
                'property_type' => 'Single Family',
                'listing_type' => 'sale',
                'price' => 279000,
                'address' => '18102 Timber Forest Drive',
                'city' => 'Humble', 'state' => 'Texas', 'zip' => '77346',
                'subdivision' => 'Atascocita',
                'bedrooms' => 3, 'full_bathrooms' => 2, 'half_bathrooms' => 0,
                'square_feet' => 1820, 'lot_size' => 6800, 'year_built' => 2007,
                'description' => "Well-maintained single story in Atascocita. Open living area, updated kitchen, and large fenced backyard. Close to Lake Houston and top-rated schools.",
                'features' => array_merge($defaultFeatures, ['Carpet', 'Mature Trees']),
                'photo' => 'humble.jpeg',
                'latitude' => 30.0088, 'longitude' => -95.2619,
            ],
            [
                'title' => 'Family Home in Jersey Village',
                'property_type' => 'Single Family',
                'listing_type' => 'sale',
                'price' => 395000,
                'address' => '15802 Lakeview Drive',
                'city' => 'Jersey Village', 'state' => 'Texas', 'zip' => '77040',
                'subdivision' => 'Jersey Village',
                'bedrooms' => 4, 'full_bathrooms' => 2, 'half_bathrooms' => 1,
                'square_feet' => 2420, 'lot_size' => 7800, 'year_built' => 2001,
                'description' => "Established Jersey Village home with a golf-course adjacent lot. Updated kitchen, hardwood floors, and a large covered patio ideal for entertaining.",
                'features' => array_merge($defaultFeatures, ['Hardwood Floors', 'Covered Patio', 'Fireplace']),
                'photo' => 'jersey-village.jpeg',
                'latitude' => 29.8891, 'longitude' => -95.5675,
            ],
            [
                'title' => 'Spacious Family Home in Katy',
                'property_type' => 'Single Family',
                'listing_type' => 'sale',
                'price' => 429000,
                'address' => '1823 Prairie View Drive',
                'city' => 'Katy', 'state' => 'Texas', 'zip' => '77494',
                'subdivision' => 'Cinco Ranch',
                'bedrooms' => 4, 'full_bathrooms' => 2, 'half_bathrooms' => 1,
                'square_feet' => 2450, 'lot_size' => 7200, 'year_built' => 2015,
                'description' => "Bright, open floor plan with an updated kitchen and plenty of natural light. Walking distance to award-winning Katy ISD schools and neighborhood parks.",
                'features' => array_merge($defaultFeatures, ['Granite Countertops', 'Stainless Steel Appliances', 'Covered Patio', 'Walk-In Closet']),
                'photo' => 'katy.jpeg',
                'latitude' => 29.7858, 'longitude' => -95.8245,
            ],
            [
                'title' => 'Luxury Home in Memorial',
                'property_type' => 'Single Family',
                'listing_type' => 'sale',
                'price' => 925000,
                'address' => '520 Memorial Drive',
                'city' => 'Houston', 'state' => 'Texas', 'zip' => '77024',
                'subdivision' => 'Memorial',
                'bedrooms' => 5, 'full_bathrooms' => 4, 'half_bathrooms' => 1,
                'square_feet' => 4180, 'lot_size' => 10500, 'year_built' => 2019,
                'description' => "Stunning luxury home in the heart of Memorial. Chef's kitchen, wine room, and resort-style backyard with pool and outdoor kitchen. Minutes from Memorial Park and the Galleria.",
                'features' => array_merge($defaultFeatures, ['Swimming Pool', 'Hot Tub', 'Fireplace', 'Hardwood Floors', 'Security System', 'Smart Home']),
                'photo' => 'memorial.jpeg',
                'latitude' => 29.7641, 'longitude' => -95.4661,
            ],
            [
                'title' => 'Family Home in Missouri City',
                'property_type' => 'Single Family',
                'listing_type' => 'sale',
                'price' => 349000,
                'address' => '4215 Sienna Parkway',
                'city' => 'Missouri City', 'state' => 'Texas', 'zip' => '77459',
                'subdivision' => 'Sienna Plantation',
                'bedrooms' => 4, 'full_bathrooms' => 2, 'half_bathrooms' => 1,
                'square_feet' => 2380, 'lot_size' => 7100, 'year_built' => 2014,
                'description' => "Well-appointed home in Sienna Plantation with community pools, parks, and trails. Open-concept living with a game room upstairs and covered back patio.",
                'features' => array_merge($defaultFeatures, ['Covered Patio', 'Walk-In Closet', 'Tile Floors']),
                'photo' => 'missouri-city.jpeg',
                'latitude' => 29.5486, 'longitude' => -95.5377,
            ],
            [
                'title' => 'Two-Story Home in Spring',
                'property_type' => 'Single Family',
                'listing_type' => 'sale',
                'price' => 295000,
                'address' => '2806 Springwoods Village Parkway',
                'city' => 'Spring', 'state' => 'Texas', 'zip' => '77386',
                'subdivision' => 'Springwoods Village',
                'bedrooms' => 3, 'full_bathrooms' => 2, 'half_bathrooms' => 1,
                'square_feet' => 2040, 'lot_size' => 5500, 'year_built' => 2018,
                'description' => "Newer two-story home in vibrant Springwoods Village. Walkable to CityPlace with shops, restaurants, and parks. Energy-efficient build with tankless water heater.",
                'features' => array_merge($defaultFeatures, ['Smart Home', 'Tile Floors']),
                'photo' => 'spring.jpeg',
                'latitude' => 30.0730, 'longitude' => -95.3908,
            ],
            [
                'title' => 'Executive Home in Sugar Land',
                'property_type' => 'Single Family',
                'listing_type' => 'sale',
                'price' => 625000,
                'address' => '4820 Lake Pointe Drive',
                'city' => 'Sugar Land', 'state' => 'Texas', 'zip' => '77479',
                'subdivision' => 'Greatwood',
                'bedrooms' => 5, 'full_bathrooms' => 3, 'half_bathrooms' => 1,
                'square_feet' => 3480, 'lot_size' => 9200, 'year_built' => 2016,
                'description' => "Executive home in sought-after Greatwood. Soaring entry, formal dining, and a media room. Backyard oasis with pool and summer kitchen. Top-rated Fort Bend ISD schools.",
                'features' => array_merge($defaultFeatures, ['Swimming Pool', 'Fireplace', 'Granite Countertops', 'Walk-In Closet', 'Hardwood Floors']),
                'photo' => 'sugar-land.jpeg',
                'latitude' => 29.6196, 'longitude' => -95.6349,
            ],
            [
                'title' => 'Country-Style Home in Tomball',
                'property_type' => 'Single Family',
                'listing_type' => 'sale',
                'price' => 359000,
                'address' => '22318 Spring Creek Road',
                'city' => 'Tomball', 'state' => 'Texas', 'zip' => '77375',
                'subdivision' => 'Woodtrace',
                'bedrooms' => 4, 'full_bathrooms' => 2, 'half_bathrooms' => 1,
                'square_feet' => 2610, 'lot_size' => 8600, 'year_built' => 2013,
                'description' => "Charming country-style home on a large lot in gated Woodtrace. Covered front porch, vaulted ceilings, and walking trails throughout the community.",
                'features' => array_merge($defaultFeatures, ['Mature Trees', 'Covered Patio', 'Fireplace']),
                'photo' => 'tomball.jpeg',
                'latitude' => 30.0972, 'longitude' => -95.6162,
            ],
        ];

        foreach ($items as $item) {
            $image = "real-estate-highlights/{$item['photo']}";
            $images = Storage::disk('public')->exists($image) ? [$image] : [];

            RealEstateListing::updateOrCreate(
                ['title' => $item['title']],
                [
                    'developer' => null,
                    'property_type' => $item['property_type'],
                    'listing_type' => $item['listing_type'],
                    'price' => $item['price'],
                    'address' => $item['address'],
                    'city' => $item['city'],
                    'state' => $item['state'],
                    'zip' => $item['zip'],
                    'subdivision' => $item['subdivision'],
                    'latitude' => $item['latitude'],
                    'longitude' => $item['longitude'],
                    'bedrooms' => $item['bedrooms'],
                    'full_bathrooms' => $item['full_bathrooms'],
                    'half_bathrooms' => $item['half_bathrooms'],
                    'square_feet' => $item['square_feet'],
                    'lot_size' => $item['lot_size'],
                    'year_built' => $item['year_built'],
                    'description' => $item['description'],
                    'features' => $item['features'],
                    'images' => $images,
                    'main_image_index' => 0,
                    'status' => 'active',
                ]
            );
        }

        $this->command->info('Real estate listings seeded: ' . RealEstateListing::count());
    }
}
